### ISSUE TITLE
Publish container to GitHub Container Registry

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#855]
Now that the GitHub Container Registry is in public beta (https://github.blog/2020-09-01-introducing-github-container-registry/), we could publish our new image to that registry, instead of relying on docker hub. 

That would allow us to automate publishing the container and should be easier to maintain.

**Comment by j4v** [comment]
@ramimac @rossja @thommor thoughts?

**Comment by thommor** [comment]
I don't see any reason why we shouldn't do this.

I would still suggest publishing to docker hub as well though.

**Comment by rossja** [comment]
Agreed.

**Comment by pperzyna** [comment]
@rossja @thommor  Please check my PR

**Comment by thommor** [comment]
I'm not up to scratch with GitHub actions but it looks fine to me. I'll let @rossja give their thoughts before I mark it as reviewed.

**Comment by pperzyna** [comment]
Unfortunately, The automatically generated GITHUB_TOKEN will not work for authentication for the initial release. It will require creating the ghcr.io/nccgroup/scoutsuite:latest manual for the first time.

**Comment by pperzyna** [comment]
@rossja any update?

**Comment by rossja** [comment]
sorry for the loooong delay on this. had a lot going on. working through the backlog now.

**Comment by pperzyna** [comment]
@rossja ping

**Comment by rossja** [comment]
This totally makes sense. I'll start working on it.

**Comment by rossja** [comment]
annnnd...it's been forever. sorry. working through this now. one reason for the long delay is that i've been looking into completely restructuring the way the docker images work to significantly reduce the size of the image (right now it's ~4gb). planning to create separate images for each of the clouds (aws, azure, ibm, etc.) rather than the all-in-one that we currently use.

**Comment by Techbrunch** [comment]
@rossja Would it be possible to publish the version 5.12.0 to DockerHub, the current version is 5.11.0

**Comment by rossja** [comment]
@Techbrunch. yep. i'll build out today. I've completely reworked how the docker stuff builds, and am ready to merge it in, but need to figure out the best way to do that because so much changed for it. (Part of that change is also to number the dockerhub images based on the version of Scoutsuite they include, btw).

**Comment by rossja** [comment]
built and pushed

**Comment by Techbrunch** [comment]
@rossja How can I use the new image ? I see that you pushed `base-latest` 17 days ago but `base` was last pushed 4 month ago ?

**Comment by rossja** [comment]
@Techbrunch : good catch! i had a bug in my tag script, so was naming everything into separate repositories rather than the ncc-scoutsuite one. i've fixed that now and have pushed the updates to the right spot.

**Comment by Techbrunch** [comment]
@rossja am I looking in the wrong place ? I'm still seeing the old version here: https://registry.hub.docker.com/layers/rossja/ncc-scoutsuite/latest/images/sha256-4455369d7eeb53bb840facd67e0adc6426d5166bcfaf2a4e378082a4e40dafa7?context=explore

**Comment by rossja** [comment]
ah! yeah, that should go to ncc-scoutsuite:base-latest. i didn't update ncc-scoutsuite:latest to point to that in the tags when i restructured. i've added that to the tag script now -- but it will have the potentially unexpected side effect of NOT including aws by default (aws is in ncc-scoutsuite:aws-latest, same with the other respective clouds).
